server:
  port: ${sp.purchase}
spring:
  config:
    import:
      - "optional:nacos:system.yaml?group=DEFAULT_GROUP&refreshEnabled=true"
      - "optional:nacos:data-source.yaml?group=DEFAULT_GROUP&refreshEnabled=true"
      - "optional:nacos:third-services.yaml?group=DEFAULT_GROUP&refreshEnabled=true"
      - "optional:nacos:key-config.yaml?group=DEFAULT_GROUP&refreshEnabled=true"
  application:
    name: ${sn.purchase}
  cloud:
    nacos:
      server-addr: ${nacos.addr:127.0.0.1:8848}
      config:
        server-addr: ${nacos.addr:127.0.0.1:8848}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/zo_psi?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      keep-alive: true
      phy-max-use-count: 1000000

#    routes:
#      - name: 核销单
#        serviceName: ${sn.capital}
#        namespaceId: ${nacos.namespace}
#        location: /v2/api-docs?group=capital
#      - name: 声明式CPP
#        serviceName: ${sn.cpp}
#        namespaceId: ${nacos.namespace}
#        location: /v2/api-docs?group=cpp
#      - name: 登录服务
#        serviceName: ${sn.login}
#        namespaceId: ${nacos.namespace}
#        location: /v2/api-docs?group=login

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


seata:
  enabled: false

