server:
  port: ${sp.moneytransfer}
spring:
  config:
    import:
      - "optional:nacos:system.yaml?group=DEFAULT_GROUP&refreshEnabled=true"
      - "optional:nacos:data-source.yaml?group=DEFAULT_GROUP&refreshEnabled=true"
      - "optional:nacos:third-services.yaml?group=DEFAULT_GROUP&refreshEnabled=true"
      - "optional:nacos:key-config.yaml?group=DEFAULT_GROUP&refreshEnabled=true"
  application:
    name: ${sn.moneytransfer}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      server-addr: ${nacos.addr:127.0.0.1:8848}
      config:
        server-addr: ${nacos.addr:127.0.0.1:8848}
      discovery:
        ip: 127.0.0.1
        port: 18500
