services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms512m -Xmx512m -Djenkins.install.runSetupWizard=false
    ports:
      - "8380:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - ./jenkins/maven_m2:/root/.m2
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net
    restart: always

networks:
  jenkins-net:
    driver: bridge
