server:
  port: ${sp.finance}
spring:
  config:
    import:
      - "optional:nacos:system.yaml?group=DEFAULT_GROUP&refreshEnabled=true"
      - "optional:nacos:data-source.yaml?group=DEFAULT_GROUP&refreshEnabled=true"
      - "optional:nacos:third-services.yaml?group=DEFAULT_GROUP&refreshEnabled=true"
      - "optional:nacos:key-config.yaml?group=DEFAULT_GROUP&refreshEnabled=true"
  cloud:
    nacos:
      server-addr: ${nacos.addr:127.0.0.1:8848}
      config:
        server-addr: ${nacos.addr:127.0.0.1:8848}
  application:
    name: ${sn.finance}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# pdf配置
pdf:
  # fop配置文件路径
  conf: ./config/fop.xconf
  # xsl-fo模板路径（目录）
  template: ./config/freemarker

logging:
  level:
    # MyBatis SQL 执行细节（包含SQL语句、参数、结果）
    org.mybatis: DEBUG
    # 数据库连接池（如Druid）的交互日志
    com.alibaba.druid: DEBUG
    # JDBC 底层交互日志（可按需开启，日志量较大）
    java.sql: DEBUG
    # 你的Mapper接口包路径（输出Mapper方法的调用细节）
    com.zeroone.star.finance.mapper: DEBUG
